language: rust
matrix:
  fast_finish: true
  allow_failure:
      - rust: nightly
  include:
    # =====================================================================
    # Stable
    # =====================================================================
    - rust: stable
      name: netlink-sys
      script:
        - cd netlink-sys
        - cargo test
        - cargo test --features mio_support
        - cargo test --features tokio_support

    - rust: stable
      name: netlink-packet-core
      script:
        - cd netlink-packet-core
        - cargo test

    - rust: stable
      name: netlink-packet-audit
      script:
        - cd netlink-packet-audit
        - cargo test

    - rust: stable
      name: netlink-packet-route
      script:
        - cd netlink-packet-route
        - cargo test

    - rust: stable
      name: netlink-proto
      script:
        - cd netlink-proto
        - cargo test
        - cargo test --features workaround-audit-bug

    - rust: stable
      name: rtnetlink
      script:
        - cd rtnetlink
        - cargo test

    - rust: stable
      name: audit
      script:
        - cd audit
        - cargo test

    # =====================================================================
    # Nightly
    # =====================================================================
    - rust: nightly
      name: nightly netlink-sys
      before_script:
        - rustup component add clippy
      script:
          - cargo clippy --all-features

    - rust: nightly
      name: nightly netlink-packet-core
      before_script:
        - rustup component add clippy
      script:
          - cargo clippy

    - rust: nightly
      name: nightly netlink-packet-audit
      before_script:
        - rustup component add clippy
      script:
          - cargo clippy

    - rust: nightly
      name: nightly netlink-packet-route
      before_script:
        - rustup component add clippy
      script:
          - cargo clippy

    - rust: nightly
      name: nightly netlink-proto
      before_script:
        - rustup component add clippy
      script:
          - cargo clippy

    - rust: nightly
      name: nightly netlink-proto
      before_script:
        - rustup component add clippy
      script:
          - cargo clippy

    - rust: nightly
      name: rustfmt
      before_script:
        - rustup component add rustfmt
      script:
          - cargo fmt --all -- --check
